name: maps

on:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install GraphicsMagicks library
      run: sudo apt-get install graphicsmagick

    - name: Generate Public folder
      run: ./gen_public.sh

    - name: Deploy to Public branch
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: public
        FOLDER: public
